# Use the official Node.js image as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY client/package*.json ./

# Install frontend dependencies
RUN npm install

# Copy the rest of the frontend code
COPY client/ .

# Build the frontend app
RUN npm run build

# Expose the frontend port
EXPOSE 3000

# Start the frontend server
CMD ["npm", "start"]