# Use the official Node.js image as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY server/package*.json ./

# Install backend dependencies
RUN npm install

# Copy the rest of the backend code
COPY server/ .

# Expose the backend port
EXPOSE 5001

# Start the backend server
CMD ["npm", "start"]